<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Modules\Academic\Models\Student;
use App\Modules\Academic\Models\Classroom;
use App\Modules\Yayasan\Models\Unit;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;

class StudentTkKraksaanSeeder extends Seeder
{
    public function run(): void
    {
        $unit = Unit::where('code', 'TK-KRA')
            ->orWhere(function ($q) {
                $q->where('name', 'LIKE', '%TK%')->where('name', 'LIKE', '%Kraksaan%');
            })
            ->first();

        if (!$unit) {
            echo "Unit TK Namira Kraksaan (TK-KRA) tidak ditemukan.\n";
            return;
        }
        $unitId = $unit->id;

        $role = DB::table('roles')->where('name', 'siswa')->orWhere('name', 'student')->first();
        $roleId = $role ? $role->id : null;

        $studentsData = array (
  0 => 
  array (
    'full_name' => 'ABIDAH ADRISTI ALESHA SHAQUEENA HASAN',
    'nis' => '',
    'nisn' => '3207035644',
    'gender' => 'P',
    'pob' => 'SITUBONDO',
    'dob' => '2020-12-11',
    'address' => 'DUSUN SUKUNAN, Sukokerto, Kec. Pajarakan',
    'parent_name' => 'M. IRFAN HASAN SIDIK',
    'parent_phone' => '082336697833',
    'email' => 'abidah@namira.school',
    'classroom_name' => 'A2',
  ),
  1 => 
  array (
    'full_name' => 'ABRIZAM ARSYAD ATHARRAYHAN',
    'nis' => '',
    'nisn' => '3201587742',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-01-27',
    'address' => 'GUBENG KERTAJAYA 4B/42, Kertajaya, Kec. Gubeng',
    'parent_name' => 'FACHRUL LAKSANA PUTRA',
    'parent_phone' => '081252532504',
    'email' => 'abrizam@namira.school',
    'classroom_name' => 'B1',
  ),
  2 => 
  array (
    'full_name' => 'ACHMAD DARWISH ZYAN ATTALLAH',
    'nis' => '',
    'nisn' => '3215729977',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-06-02',
    'address' => 'DUSUN KRAJAN, ALASSUMURLOR, Desa/Kel. Alassumur Lor, Kec. Besuk',
    'parent_name' => 'SABRI',
    'parent_phone' => '082312345675',
    'email' => 'achmad@namira.school',
    'classroom_name' => 'A2',
  ),
  3 => 
  array (
    'full_name' => 'ADEEVA OCTAVIA PUTRI HASPITA',
    'nis' => '',
    'nisn' => '3200958552',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-10-20',
    'address' => 'DUSUN PATUKANGAN, PATUKANGAN, Desa/Kel. Randutatah, Kec. Paiton',
    'parent_name' => 'SUDARMANTO',
    'parent_phone' => '081334309545',
    'email' => 'adeeva@namira.school',
    'classroom_name' => 'A2',
  ),
  4 => 
  array (
    'full_name' => 'ADIBA NUR ALESHA',
    'nis' => '',
    'nisn' => '3192580776',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-08-24',
    'address' => 'JL MT. HARYONO NO 90, Jogoyudan, Kec. Lumajang',
    'parent_name' => 'ADI PERDANA',
    'parent_phone' => '081259355054',
    'email' => 'adiba@namira.school',
    'classroom_name' => 'B4',
  ),
  5 => 
  array (
    'full_name' => 'AFIFUDDIN HASSAN',
    'nis' => '',
    'nisn' => '3191793695',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-11-29',
    'address' => 'JL PZH GENGGONG DUSUN KRAJAN, Karangbong, Kec. Pajarakan',
    'parent_name' => 'AHSAN MALIKI',
    'parent_phone' => '085236084000',
    'email' => 'afifuddin@namira.school',
    'classroom_name' => 'B1',
  ),
  6 => 
  array (
    'full_name' => 'AGISUNA YALHASANI',
    'nis' => '',
    'nisn' => '3181247445',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2018-12-19',
    'address' => 'DUSUN, KRAJAN, Desa/Kel. Karangbong, Kec. Pajarakan',
    'parent_name' => 'AHSAN HABIBI FILLAH',
    'parent_phone' => '085335611991',
    'email' => 'agisuna@namira.school',
    'classroom_name' => 'B4',
  ),
  7 => 
  array (
    'full_name' => 'AHMAD AL HUSEIN KAFFAH',
    'nis' => '',
    'nisn' => '3209806637',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-04-30',
    'address' => 'JL KH ABDURRAHMAN WAHID, SIDOMUKTI, Desa/Kel. Sidomukti, Kec. Kraksaan',
    'parent_name' => 'AHMAD RIDWAN',
    'parent_phone' => '085232043334',
    'email' => 'ahmad@namira.school',
    'classroom_name' => 'A2',
  ),
  8 => 
  array (
    'full_name' => 'AHMAD FATIH RIF\'AN AZIZ',
    'nis' => '',
    'nisn' => '3207026420',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-05-25',
    'address' => 'KAMPUNG MELAYU, KRAKSAAN WETAN, Kraksaan Wetan, Kec. Kraksaan',
    'parent_name' => 'FAHMI NUR HIDAYAT',
    'parent_phone' => '082301815399',
    'email' => 'ahmad.2@namira.school',
    'classroom_name' => 'A2',
  ),
  9 => 
  array (
    'full_name' => 'AHMAD THORIQ AL BAITY',
    'nis' => '',
    'nisn' => '3205446252',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-10-13',
    'address' => 'JLN RA KARTINI, SIDOMUKTI, Desa/Kel. Sidomukti, Kec. Kraksaan',
    'parent_name' => 'NABIL AL BAITY',
    'parent_phone' => '082342154675',
    'email' => 'ahmad.3@namira.school',
    'classroom_name' => 'A2',
  ),
  10 => 
  array (
    'full_name' => 'AISYAH ALMAHYRA PRASETYO',
    'nis' => '',
    'nisn' => '3200098890',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-04-17',
    'address' => 'PERUM PJB JL TRAVO NO.2, Desa/Kel. Sukodadi, Kec. Paiton',
    'parent_name' => 'PURNOMO TRI PARSETYO',
    'parent_phone' => '081217213310',
    'email' => 'aisyah@namira.school',
    'classroom_name' => 'B1',
  ),
  11 => 
  array (
    'full_name' => 'ALAN PUTRA HERMAWAN',
    'nis' => '',
    'nisn' => '3209242935',
    'gender' => 'L',
    'pob' => 'SIDOARJO',
    'dob' => '2020-08-04',
    'address' => 'BUNCITAN 62, BUNCITAN 62, Desa/Kel. Buncitan, Kec. Sedati',
    'parent_name' => 'ADI HERMAWAN',
    'parent_phone' => '081234543675',
    'email' => 'alan@namira.school',
    'classroom_name' => 'A2',
  ),
  12 => 
  array (
    'full_name' => 'ALESHA NAFISAH PUTRI',
    'nis' => '',
    'nisn' => '3209813846',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-11-09',
    'address' => 'JL. LETJEN S.PARMAN, SEMAMPIR, Desa/Kel. Semampir, Kec. Kraksaan',
    'parent_name' => 'KUSWANDI',
    'parent_phone' => '082131363661',
    'email' => 'alesha@namira.school',
    'classroom_name' => 'A2',
  ),
  13 => 
  array (
    'full_name' => 'ALISHA ATTHAYA MEDINA',
    'nis' => '',
    'nisn' => '3194647392',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-11-22',
    'address' => 'DUSUN UTARA, Matekan, Kec. Besuk',
    'parent_name' => 'AMINULLAH',
    'parent_phone' => '081334772477',
    'email' => 'alisha@namira.school',
    'classroom_name' => 'B4',
  ),
  14 => 
  array (
    'full_name' => 'ALISHA CHAYRA AINUR RACHMAN',
    'nis' => '',
    'nisn' => '3208552461',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-02-21',
    'address' => 'DUSUN 3, PASAR 1, Desa/Kel. Klaseman, Kec. Gending',
    'parent_name' => 'NURUL FARIDA',
    'parent_phone' => '085258893176',
    'email' => 'alisha.2@namira.school',
    'classroom_name' => 'B2',
  ),
  15 => 
  array (
    'full_name' => 'ALRIANA D GIENKA',
    'nis' => '',
    'nisn' => '3197750476',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-02-26',
    'address' => 'DUSUN, TAMAN 2, Desa/Kel. Besuk Agung, Kec. Besuk',
    'parent_name' => 'ALI HAIDAR',
    'parent_phone' => '081234446556',
    'email' => 'alriana@namira.school',
    'classroom_name' => 'B4',
  ),
  16 => 
  array (
    'full_name' => 'AMIRA BARROH ATTAQIYYAH',
    'nis' => '',
    'nisn' => '3208971578',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-12-20',
    'address' => 'DUSUN, KRAJAN, Desa/Kel. Rangkang, Kec. Kraksaan',
    'parent_name' => 'AHMAD BAHRU SALAM',
    'parent_phone' => '082345678987',
    'email' => 'amira@namira.school',
    'classroom_name' => 'A2',
  ),
  17 => 
  array (
    'full_name' => 'ANASTASIYA KANYAZEVA',
    'nis' => '',
    'nisn' => '3195642732',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-11-06',
    'address' => 'DUSUN TEGGINAH, Gunggungan Lor, Kec. Pakuniran',
    'parent_name' => 'ROVYNANTO SITANGGANG',
    'parent_phone' => '087704623642',
    'email' => 'anastasiya@namira.school',
    'classroom_name' => 'B1',
  ),
  18 => 
  array (
    'full_name' => 'ANDYRA KALEA ALNAIRA RIZKI',
    'nis' => '',
    'nisn' => '3197772226',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-08-29',
    'address' => 'DUSUN SEKAR, DESA SUMBER ANYAR, Kec. Paiton',
    'parent_name' => 'ANGGA RIZKI FAUZI',
    'parent_phone' => '082330503892',
    'email' => 'andyra@namira.school',
    'classroom_name' => 'B1',
  ),
  19 => 
  array (
    'full_name' => 'ARIENDRA NAUFAL RABBANI',
    'nis' => '',
    'nisn' => '3200747511',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-05-17',
    'address' => 'JL PAHLAWAN, Desa/Kel. Krejengan, Kec. Krejengan',
    'parent_name' => 'MOH. HOLILULLAH',
    'parent_phone' => '085855114999',
    'email' => 'ariendra@namira.school',
    'classroom_name' => 'B1',
  ),
  20 => 
  array (
    'full_name' => 'ARISHA DARITRI ALMAHYRA',
    'nis' => '',
    'nisn' => '3200098074',
    'gender' => 'P',
    'pob' => 'JOMBANG',
    'dob' => '2020-10-02',
    'address' => 'DUSUN KRAJAN, KRAJAN, Desa/Kel. Patemon Kulon, Kec. Pakuniran',
    'parent_name' => 'HENDRY ZUBEIR OKTABRYANTO',
    'parent_phone' => '0822314567897',
    'email' => 'arisha@namira.school',
    'classroom_name' => 'A2',
  ),
  21 => 
  array (
    'full_name' => 'ARKANA AIDAN ABDUL AZIZ',
    'nis' => '',
    'nisn' => '3213784442',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-02-19',
    'address' => 'JL.DR WAHIDIN 3, KANDANG JATI, Desa/Kel. Kandangjati Kulon, Kec. Kraksaan',
    'parent_name' => 'FAHMI DIMAS ABDUL AZIS',
    'parent_phone' => '081546786543',
    'email' => 'arkana@namira.school',
    'classroom_name' => 'A2',
  ),
  22 => 
  array (
    'full_name' => 'ASYIQNA NUR FATIMAH',
    'nis' => '',
    'nisn' => '3210347197',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-06-05',
    'address' => 'JINTEL, MEGALE, Desa/Kel. Megale, Kec. Kedungadem',
    'parent_name' => 'MOHAMAD ALI RIFAI',
    'parent_phone' => '082341675987',
    'email' => 'asyiqna@namira.school',
    'classroom_name' => 'A1',
  ),
  23 => 
  array (
    'full_name' => 'ATHA ABDULLAH',
    'nis' => '',
    'nisn' => '3190448316',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-08-21',
    'address' => 'DUSUN KRAJAN, Sidopekso, Kec. Kraksaan',
    'parent_name' => 'ABU BAKAR ROHIM',
    'parent_phone' => '081336900023',
    'email' => 'atha@namira.school',
    'classroom_name' => 'B2',
  ),
  24 => 
  array (
    'full_name' => 'ATHALIA MAHESHWARI FARZANA',
    'nis' => '',
    'nisn' => '3198632715',
    'gender' => 'P',
    'pob' => 'BANYUWANGI',
    'dob' => '2019-04-06',
    'address' => 'PANJI PERMAI AA-03, Mimbaan, Kec. Panji',
    'parent_name' => 'HANANTHA DWIPAYANA',
    'parent_phone' => '',
    'email' => 'athalia@namira.school',
    'classroom_name' => 'B4',
  ),
  25 => 
  array (
    'full_name' => 'ATIKA FITHRIYA TSABITA AHMAD',
    'nis' => '',
    'nisn' => '3208718886',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-08-14',
    'address' => 'DUSUN TANJUNG LOR, Desa/Kel. Karanganyar, Kec. Paiton',
    'parent_name' => 'AHMAD MUJTAHID',
    'parent_phone' => '082133008641',
    'email' => 'atika@namira.school',
    'classroom_name' => 'A2',
  ),
  26 => 
  array (
    'full_name' => 'AZKIYA KAYLA MARDHIYAH',
    'nis' => '',
    'nisn' => '3205889417',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-03-01',
    'address' => 'DUSUN KRAJAN, DUSUN KRAJAN, Desa/Kel. Jatiadi, Kec. Gending',
    'parent_name' => 'AIDO RIZAL SHOLIHIN',
    'parent_phone' => '081234564321',
    'email' => 'azkiya@namira.school',
    'classroom_name' => 'A2',
  ),
  27 => 
  array (
    'full_name' => 'BILFAQIH ASSAJID HANGGAREKSA',
    'nis' => '',
    'nisn' => '3209703004',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-09-11',
    'address' => 'DUSUN SILOLEMBU, SENTONG, Desa/Kel. Sentong, Kec. Krejengan',
    'parent_name' => 'SYAMSUL ARIFIN',
    'parent_phone' => '081231543765',
    'email' => 'bilfaqih@namira.school',
    'classroom_name' => 'A2',
  ),
  28 => 
  array (
    'full_name' => 'BINTANG MERRY ANGEL PRAMESWARI',
    'nis' => '',
    'nisn' => '3191614660',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-04-19',
    'address' => 'KRAJAN, KRAJAN I, Desa/Kel. Nogosaren, Kec. Gading',
    'parent_name' => 'EKA RIZKI NOVIAN AFFANDI',
    'parent_phone' => '082230203249',
    'email' => 'bintang@namira.school',
    'classroom_name' => 'B4',
  ),
  29 => 
  array (
    'full_name' => 'CAMELIA GHAZALA FAUZAN',
    'nis' => '',
    'nisn' => '3203676016',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-08-21',
    'address' => 'DUSUN JAWAAN, JAWAAN, Desa/Kel. Kedungcaluk, Kec. Krejengan',
    'parent_name' => 'SULSAIMAN FAUZAN',
    'parent_phone' => '082139444117',
    'email' => 'camelia@namira.school',
    'classroom_name' => 'A2',
  ),
  30 => 
  array (
    'full_name' => 'CHARISSA PUTRI EL ANWAR',
    'nis' => '',
    'nisn' => '3210760217',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-02-08',
    'address' => 'DUSUN KRAJAN, ASEMBAKOR, Desa/Kel. Asembakor, Kec. Kraksaan',
    'parent_name' => 'SYAIFUL ANWAR',
    'parent_phone' => '085258833953',
    'email' => 'charissa@namira.school',
    'classroom_name' => 'A3',
  ),
  31 => 
  array (
    'full_name' => 'CLEMIRA FACHRANA ZAHRA',
    'nis' => '',
    'nisn' => '3205357850',
    'gender' => 'P',
    'pob' => 'MOJOKERTO',
    'dob' => '2020-11-23',
    'address' => 'PERUM GREEN GARDEN D15, SUMBERLELE, Desa/Kel. Sumberlele, Kec. Kraksaan',
    'parent_name' => 'ERIC EFFENDI',
    'parent_phone' => '085234577767',
    'email' => 'clemira@namira.school',
    'classroom_name' => 'A1',
  ),
  32 => 
  array (
    'full_name' => 'DAISHA INARA LAIQANISA',
    'nis' => '',
    'nisn' => '3191070162',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-08-25',
    'address' => 'KEMBANG, Desa/Kel. Seboro, Kec. Krejengan',
    'parent_name' => 'DEDI WAHYUDI EKO PRAMANA',
    'parent_phone' => '',
    'email' => 'daisha@namira.school',
    'classroom_name' => 'B1',
  ),
  33 => 
  array (
    'full_name' => 'DELVIN DWI PUTRA FAHRIZA',
    'nis' => '',
    'nisn' => '3170328146',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2017-10-14',
    'address' => 'DUSUN, KRAJAN 2, Selogudig Wetan, Kec. Pajarakan',
    'parent_name' => 'HASAN BUSRI',
    'parent_phone' => '085258880906',
    'email' => 'delvin@namira.school',
    'classroom_name' => 'B3',
  ),
  34 => 
  array (
    'full_name' => 'DHEFIN ADELYO ATHARIQ',
    'nis' => '',
    'nisn' => '3208796851',
    'gender' => 'L',
    'pob' => 'SURABAYA',
    'dob' => '2020-12-18',
    'address' => 'GIRILAYA 8/20, BANYU URIP, Desa/Kel. Banyu Urip, Kec. Sawahan',
    'parent_name' => 'DELTON DODY ALIFADEPRABU',
    'parent_phone' => '081237689098',
    'email' => 'dhefin@namira.school',
    'classroom_name' => 'A1',
  ),
  35 => 
  array (
    'full_name' => 'DZURROTUL KHITAMI RAMADHANI',
    'nis' => '',
    'nisn' => '3205058581',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-04-26',
    'address' => 'DUSUN SUMBER, Desa/Kel. Bulu, Kec. Kraksaan',
    'parent_name' => 'MOHAMMAD ADIB',
    'parent_phone' => '082232274921',
    'email' => 'dzurrotul@namira.school',
    'classroom_name' => 'B1',
  ),
  36 => 
  array (
    'full_name' => 'EL ZAYN MUBARAK',
    'nis' => '',
    'nisn' => '3197145244',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-12-24',
    'address' => 'DUSUN, KRAJAN, Desa/Kel. Batur, Kec. Gading',
    'parent_name' => 'HUSNY MUBARAK ABDUL MUIZ',
    'parent_phone' => '085257350879',
    'email' => 'el@namira.school',
    'classroom_name' => 'B1',
  ),
  37 => 
  array (
    'full_name' => 'FAHIMA RAMADHANI',
    'nis' => '',
    'nisn' => '0191029310',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-05-11',
    'address' => 'DUSUN KRAJAN, KOTAANYAR, Kec. Kotaanyar',
    'parent_name' => 'SAIPUL BAHRI',
    'parent_phone' => '085331362000',
    'email' => 'fahima@namira.school',
    'classroom_name' => 'B2',
  ),
  38 => 
  array (
    'full_name' => 'FAREL UMAIR WIBOWO',
    'nis' => '',
    'nisn' => '3192647367',
    'gender' => 'L',
    'pob' => 'MATARAM',
    'dob' => '2019-12-31',
    'address' => 'PERUM GRIYA PALM RAHMANI CLUSTER 2 NO.19, KEBONAGUNG, Desa/Kel. Kebonagung, Kec. Kraksaan',
    'parent_name' => 'PUJI WIBOWO',
    'parent_phone' => '087824572427',
    'email' => 'farel@namira.school',
    'classroom_name' => 'B1',
  ),
  39 => 
  array (
    'full_name' => 'FATIH RIZKY RAMADHAN',
    'nis' => '',
    'nisn' => '3217853699',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-04-23',
    'address' => 'DUSUN BERINGIN, DUSUN BERINGIN, Brabe, Kec. Maron',
    'parent_name' => 'FANDA DWI APRILIANTO',
    'parent_phone' => '082237518548',
    'email' => 'fatih@namira.school',
    'classroom_name' => 'A2',
  ),
  40 => 
  array (
    'full_name' => 'FATIHA AINA SALSABILA',
    'nis' => '',
    'nisn' => '3210400627',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-01-04',
    'address' => 'DUSUN KRAJAN, RANDUJALAK, Desa/Kel. Randujalak, Kec. Besuk',
    'parent_name' => 'NUR DWIANSYAH TRIYONO PUTRA',
    'parent_phone' => '081231453675',
    'email' => 'fatiha@namira.school',
    'classroom_name' => 'A3',
  ),
  41 => 
  array (
    'full_name' => 'FREYA ZEAMALIQUE ANDRIAN',
    'nis' => '',
    'nisn' => '3191369405',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-02-16',
    'address' => 'DUSUN, KAMPUNG BARU, Desa/Kel. Sukodadi, Kec. Paiton',
    'parent_name' => 'JATIM ANDRIANTO',
    'parent_phone' => '082345674564',
    'email' => 'freya@namira.school',
    'classroom_name' => 'A1',
  ),
  42 => 
  array (
    'full_name' => 'GIANLUCA ALVARO XAVIER BIL FAQIH',
    'nis' => '',
    'nisn' => '3199417046',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-11-22',
    'address' => 'PERUM BUMI BULU INDAH BLOK B 01, Desa/Kel. Bulu, Kec. Kraksaan',
    'parent_name' => 'GEOFARI ADE REZA BF',
    'parent_phone' => '085156089180',
    'email' => 'gianluca@namira.school',
    'classroom_name' => 'B1',
  ),
  43 => 
  array (
    'full_name' => 'GIYANDRA ANINDITA JAILANI',
    'nis' => '',
    'nisn' => '3201928380',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-01-03',
    'address' => 'DUSUN KALIURANG, Sokaan, Kec. Krejengan',
    'parent_name' => 'MOH JAILANI',
    'parent_phone' => '085259259440',
    'email' => 'giyandra@namira.school',
    'classroom_name' => 'B1',
  ),
  44 => 
  array (
    'full_name' => 'HANIF MAULANA YUSUF',
    'nis' => '',
    'nisn' => '3193691870',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-04-12',
    'address' => 'PERUM BUMI BULU INDAH BLOK P-4, BULU, Kec. Kraksaan',
    'parent_name' => 'KARDIAN NASIR DWI PRASETYO',
    'parent_phone' => '085236742959',
    'email' => 'hanif@namira.school',
    'classroom_name' => 'B1',
  ),
  45 => 
  array (
    'full_name' => 'HANIN FADIA SYAHIRA',
    'nis' => '',
    'nisn' => '3202695486',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-01-21',
    'address' => 'DUSUN 3 PASAR DUA, Klaseman, Kec. Gending',
    'parent_name' => 'HISYAM FARIH',
    'parent_phone' => '085204848557',
    'email' => 'hanin@namira.school',
    'classroom_name' => 'A3',
  ),
  46 => 
  array (
    'full_name' => 'HANIN HIMAYATUL ILAH',
    'nis' => '',
    'nisn' => '3200080580',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-08-07',
    'address' => 'DUSUN OPO-OPO LOR, Desa/Kel. Opo Opo, Kec. Krejengan',
    'parent_name' => 'SHOHIBUL HUDA',
    'parent_phone' => '085234343336',
    'email' => 'hanin.2@namira.school',
    'classroom_name' => 'A3',
  ),
  47 => 
  array (
    'full_name' => 'HANUM ALMEERA AZZAHRA',
    'nis' => '',
    'nisn' => '3204984084',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-01-23',
    'address' => 'JL AHMAD YANI GANG KENARI 1/6, MANGUNHARJO, Kec. Mayangan',
    'parent_name' => 'MIFTACH SUSANTO',
    'parent_phone' => '082132767635',
    'email' => 'hanum@namira.school',
    'classroom_name' => 'B1',
  ),
  48 => 
  array (
    'full_name' => 'HASAN ABDUL MALIK',
    'nis' => '',
    'nisn' => '3200825850',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-08-20',
    'address' => 'JL MAYJEN SUTOYO, PATOKAN, Desa/Kel. Patokan, Kec. Kraksaan',
    'parent_name' => 'MOH. FAUZI',
    'parent_phone' => '082315647876',
    'email' => 'hasan@namira.school',
    'classroom_name' => 'A1',
  ),
  49 => 
  array (
    'full_name' => 'HISYAM BALYA NAZEEH',
    'nis' => '',
    'nisn' => '3205265886',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-11-18',
    'address' => 'DUSUN KRAJAN III, CONDONG, Desa/Kel. Condong, Kec. Gading',
    'parent_name' => 'AQIQ ZAMAN FIRDAUS',
    'parent_phone' => '081231546897',
    'email' => 'hisyam@namira.school',
    'classroom_name' => 'A3',
  ),
  50 => 
  array (
    'full_name' => 'IKRIMA SHAQUEENA NURDIN',
    'nis' => '',
    'nisn' => '3207364628',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-01-14',
    'address' => 'DUSUN, KEMBANG, Desa/Kel. Jambangan, Kec. Besuk',
    'parent_name' => 'NURUDIN AS\'AT',
    'parent_phone' => '082336418421',
    'email' => 'ikrima@namira.school',
    'classroom_name' => 'B1',
  ),
  51 => 
  array (
    'full_name' => 'ILMIRA FATIMAH AZZAHRA',
    'nis' => '',
    'nisn' => '3204237884',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-05-13',
    'address' => 'JL COKROAMINOTO GG.03 NO.225, KANIGARAN, Desa/Kel. Kebonsari Kulon, Kec. Kanigaran',
    'parent_name' => 'M GHORIB ANWAR',
    'parent_phone' => '081235252827',
    'email' => 'ilmira@namira.school',
    'classroom_name' => 'A1',
  ),
  52 => 
  array (
    'full_name' => 'JINAN ZELMIRA ANDANILA',
    'nis' => '',
    'nisn' => '3208566543',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-12-25',
    'address' => 'DUSUN KRAJAN, KOTAANYAR, Desa/Kel. Kotaanyar, Kec. Kotaanyar',
    'parent_name' => 'FITRAH RAMADHANI',
    'parent_phone' => '085955203909',
    'email' => 'jinan@namira.school',
    'classroom_name' => 'A3',
  ),
  53 => 
  array (
    'full_name' => 'JINANI FARADIS NAQSYA HIDAYATULLAH',
    'nis' => '',
    'nisn' => '3195652812',
    'gender' => 'P',
    'pob' => 'SURABAYA',
    'dob' => '2019-10-16',
    'address' => 'DUSUN KRAMAT, Wangkal, Kec. Gading',
    'parent_name' => 'RAHMAD HIDAYAT',
    'parent_phone' => '087757769082',
    'email' => 'jinani@namira.school',
    'classroom_name' => 'B2',
  ),
  54 => 
  array (
    'full_name' => 'KAESANG AGNIBRATA PUTRA PRATAMA',
    'nis' => '',
    'nisn' => '3195757957',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-11-05',
    'address' => 'DUSUN KRAJAN II, Dandang, Kec. Gading',
    'parent_name' => 'PENI YUDHA PRATAMA',
    'parent_phone' => '082299016677',
    'email' => 'kaesang@namira.school',
    'classroom_name' => 'B4',
  ),
  55 => 
  array (
    'full_name' => 'KAINDRA IRSYAD RAMADHAN',
    'nis' => '',
    'nisn' => '3200845452',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-05-15',
    'address' => 'DUSUN KARANG DAMPIT GG 04, KARANG DAMPIT, Desa/Kel. Kebonagung, Kec. Kraksaan',
    'parent_name' => 'EKO PURWANTO WIJAYA HANDOKO',
    'parent_phone' => '085233208783',
    'email' => 'kaindra@namira.school',
    'classroom_name' => 'A3',
  ),
  56 => 
  array (
    'full_name' => 'KALANDRA HAMIZAN ALFAREZI',
    'nis' => '',
    'nisn' => '3195670348',
    'gender' => 'L',
    'pob' => 'WONOSOBO',
    'dob' => '2019-10-15',
    'address' => 'PERUM GREEN GARDEN NO.B7, Sumberlele, Kec. Kraksaan',
    'parent_name' => 'TAUFIQ ADI NUGROHO',
    'parent_phone' => '087739749629',
    'email' => 'kalandra@namira.school',
    'classroom_name' => 'B2',
  ),
  57 => 
  array (
    'full_name' => 'KEINARA HAFSHA ADZKIYA FARHANA',
    'nis' => '',
    'nisn' => '3203099873',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-09-21',
    'address' => 'JL SUNAN KALIJAGA NO 36, JL SUNAN KALIJAGA NO 36, Desa/Kel. Kraksaan Wetan, Kec. Kraksaan',
    'parent_name' => 'FARHANA IMRON',
    'parent_phone' => '081231234543',
    'email' => 'keinara@namira.school',
    'classroom_name' => 'A3',
  ),
  58 => 
  array (
    'full_name' => 'KEITA DYRA YUSANDY',
    'nis' => '',
    'nisn' => '3185721824',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2018-11-30',
    'address' => 'DUSUN, TENGAH, Desa/Kel. Krucil, Kec. Krucil',
    'parent_name' => 'DANDY YUSANDY',
    'parent_phone' => '082345213456',
    'email' => 'keita@namira.school',
    'classroom_name' => 'B3',
  ),
  59 => 
  array (
    'full_name' => 'KHALISA DAFIYAH YAMINA',
    'nis' => '',
    'nisn' => '3217165368',
    'gender' => 'P',
    'pob' => 'GRESIK',
    'dob' => '2021-04-22',
    'address' => 'SINDUJOYO 10C/62, LUMPUR, Desa/Kel. Lumpur, Kec. Gresik',
    'parent_name' => 'FAISAL KURNIAWAN RAHARJO',
    'parent_phone' => '082230991456',
    'email' => 'khalisa@namira.school',
    'classroom_name' => 'A3',
  ),
  60 => 
  array (
    'full_name' => 'KHALISATUL JANNAH',
    'nis' => '',
    'nisn' => '3198224408',
    'gender' => 'P',
    'pob' => 'SELANGOR',
    'dob' => '2019-06-23',
    'address' => 'DUSUN MANGAR, MANGAR, Desa/Kel. Tanjung, Kec. Pajarakan',
    'parent_name' => 'MOHAMMAD ALI',
    'parent_phone' => '082334489113',
    'email' => 'khalisatul@namira.school',
    'classroom_name' => 'B2',
  ),
  61 => 
  array (
    'full_name' => 'KIARA NUR APRILIA NATHANIA',
    'nis' => '',
    'nisn' => '3218694384',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-04-12',
    'address' => 'DUSUN KRAJAN, SUKO, Desa/Kel. Suko, Kec. Maron',
    'parent_name' => 'YANUAR ARIF NUR SUDRAJAT',
    'parent_phone' => '082341675890',
    'email' => 'kiara@namira.school',
    'classroom_name' => 'A2',
  ),
  62 => 
  array (
    'full_name' => 'KINARIAN NADIRA SHANUM',
    'nis' => '',
    'nisn' => '3203179584',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-03-21',
    'address' => 'JL WR SUPRATMAN, PERUM BUMI BULU INDAH, Desa/Kel. Bulu, Kec. Kraksaan',
    'parent_name' => 'KUSNADI',
    'parent_phone' => '08113415956',
    'email' => 'kinarian@namira.school',
    'classroom_name' => 'B2',
  ),
  63 => 
  array (
    'full_name' => 'KIRANA SHIRLY ADREENA',
    'nis' => '',
    'nisn' => '3202076712',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-01-09',
    'address' => 'DUSUN, NANGGER, Desa/Kel. Alas Kandang, Kec. Besuk',
    'parent_name' => 'SUKITO ST',
    'parent_phone' => '082675987436',
    'email' => 'kirana@namira.school',
    'classroom_name' => 'A1',
  ),
  64 => 
  array (
    'full_name' => 'LABIB NUHA KHAYRI FAEYZA AL GHANI',
    'nis' => '',
    'nisn' => '3217116275',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-02-24',
    'address' => 'DUSUN MATEKAN TENGAH, DUSUN MATEKAN TENGAH, Desa/Kel. Matekan, Kec. Besuk',
    'parent_name' => 'HERMANTO SOIKUN',
    'parent_phone' => '082234564321',
    'email' => 'labib@namira.school',
    'classroom_name' => 'A3',
  ),
  65 => 
  array (
    'full_name' => 'LABIQA RAIHANUN NUHA',
    'nis' => '',
    'nisn' => '3182537764',
    'gender' => 'P',
    'pob' => 'PESISIR SELATAN',
    'dob' => '2018-12-10',
    'address' => 'JL. MIG RAYA NO 2, MELONG, Desa/Kel. Melong, Kec. Cimahi Selatan',
    'parent_name' => 'NANANG ADI WIJAYA',
    'parent_phone' => '081266321600',
    'email' => 'labiqa@namira.school',
    'classroom_name' => 'B4',
  ),
  66 => 
  array (
    'full_name' => 'LU\'LU\'AH MAKNUNAH FIRDAUSIYAH ABDULLAH',
    'nis' => '',
    'nisn' => '3199534763',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-10-18',
    'address' => 'DUSUN TALAR I, TALAR, Desa/Kel. Sumberan, Kec. Besuk',
    'parent_name' => 'ABDULLAH YASIN',
    'parent_phone' => '085534678654',
    'email' => 'luluah@namira.school',
    'classroom_name' => 'B4',
  ),
  67 => 
  array (
    'full_name' => 'MALIKA ZAHIRA SALAMAH',
    'nis' => '',
    'nisn' => '3201438480',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-06-04',
    'address' => 'DUSUN KRAJAN, Rangkang, Kec. Kraksaan',
    'parent_name' => 'MOHAMMAD DIMYATI',
    'parent_phone' => '081232478999',
    'email' => 'malika@namira.school',
    'classroom_name' => 'B4',
  ),
  68 => 
  array (
    'full_name' => 'MAYESHA RIZANINDYA WARDANA',
    'nis' => '',
    'nisn' => '3190495721',
    'gender' => 'P',
    'pob' => 'MALANG',
    'dob' => '2019-05-25',
    'address' => 'JL DANAU KERINCI V G6 G-14, SAWOJAJAR, Kec. Kedungkandang',
    'parent_name' => 'MOCH. RIZAD EKA WARDANA',
    'parent_phone' => '081336729340',
    'email' => 'mayesha@namira.school',
    'classroom_name' => 'B3',
  ),
  69 => 
  array (
    'full_name' => 'MELVIANO KEENAN MUBARAK',
    'nis' => '',
    'nisn' => '3206539564',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-04-25',
    'address' => 'DUSUN KRAJAN, DUSUN KRAJAN, Tulupari, Kec. Tiris',
    'parent_name' => 'RIZAL MUBARAK SUKMANTARA',
    'parent_phone' => '082131011181',
    'email' => 'melviano@namira.school',
    'classroom_name' => 'A3',
  ),
  70 => 
  array (
    'full_name' => 'MEYKHAYLA RAMADHANI KIRANA',
    'nis' => '',
    'nisn' => '3193540797',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-05-27',
    'address' => 'DUSUN, KRAJAN, Desa/Kel. Bulu, Kec. Kraksaan',
    'parent_name' => 'ABDUL WAHAB SYA\'RONI',
    'parent_phone' => '082132761702',
    'email' => 'meykhayla@namira.school',
    'classroom_name' => 'B3',
  ),
  71 => 
  array (
    'full_name' => 'MIKAYLA AFKARINA DYANATUL AZIZAH',
    'nis' => '',
    'nisn' => '3199965864',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-03-04',
    'address' => 'JABUNGSARI, KRAJAN, Jabungsisir, Kec. Paiton',
    'parent_name' => 'MUHAMMAD AZIZ WIJIANTORO',
    'parent_phone' => '',
    'email' => 'mikayla@namira.school',
    'classroom_name' => 'B1',
  ),
  72 => 
  array (
    'full_name' => 'MOHAMMAD GERALDI ARINOMO',
    'nis' => '',
    'nisn' => '3205178546',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-08-28',
    'address' => 'JL DR SUTOMO, SUMBERLELE, Desa/Kel. Sumberlele, Kec. Kraksaan',
    'parent_name' => 'ROZIQIN ARINOMO',
    'parent_phone' => '081335995775',
    'email' => 'mohammad@namira.school',
    'classroom_name' => 'A3',
  ),
  73 => 
  array (
    'full_name' => 'MUCHAMMAD ABIZAR RAZKA SABILLA',
    'nis' => '',
    'nisn' => '3192003458',
    'gender' => 'L',
    'pob' => 'SURABAYA',
    'dob' => '2019-03-21',
    'address' => 'KUTISARI SELATAN 1/5 B, KUTISARI SELATAN, Desa/Kel. Kutisari, Kec. Tenggilis Mejoyo',
    'parent_name' => 'BILLY HERY SABILLA',
    'parent_phone' => '085342342123',
    'email' => 'muchammad@namira.school',
    'classroom_name' => 'B3',
  ),
  74 => 
  array (
    'full_name' => 'MUHAMMAD AIMAR ALHABSYI',
    'nis' => '',
    'nisn' => '3201452152',
    'gender' => 'L',
    'pob' => 'MEDAN',
    'dob' => '2020-07-10',
    'address' => 'PERUM SEMAMPIR INDAH I BLOK A1, SEMAMPIR, Desa/Kel. Semampir, Kec. Kraksaan',
    'parent_name' => 'UMAR HELMI',
    'parent_phone' => '081230089139',
    'email' => 'muhammad@namira.school',
    'classroom_name' => 'B3',
  ),
  75 => 
  array (
    'full_name' => 'MUHAMMAD AKHYAR FATTAN',
    'nis' => '',
    'nisn' => '3208322879',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-06-02',
    'address' => 'DUSUN PRASI SELATAN, Prasi, Kec. Gading',
    'parent_name' => 'SAFRAJI',
    'parent_phone' => '085233242903',
    'email' => 'muhammad.2@namira.school',
    'classroom_name' => 'A1',
  ),
  76 => 
  array (
    'full_name' => 'MUHAMMAD ALVINO SYAPUTRA',
    'nis' => '',
    'nisn' => '3209831383',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-12-15',
    'address' => 'DUSUN KRAJAN, BULU, Desa/Kel. Bulu, Kec. Kraksaan',
    'parent_name' => 'ABDUL WAHAB SYA\'RONI',
    'parent_phone' => '081231453675',
    'email' => 'muhammad.3@namira.school',
    'classroom_name' => 'A3',
  ),
  77 => 
  array (
    'full_name' => 'MUHAMMAD AMAR ALHABSYI',
    'nis' => '',
    'nisn' => '3209532023',
    'gender' => 'L',
    'pob' => 'MEDAN',
    'dob' => '2020-07-10',
    'address' => 'PERUM SEMAMPIR INDAH I BLOK A1, SEMAMPIR, Desa/Kel. Semampir, Kec. Kraksaan',
    'parent_name' => 'UMAR HELMI',
    'parent_phone' => '081230089139',
    'email' => 'muhammad.4@namira.school',
    'classroom_name' => 'A1',
  ),
  78 => 
  array (
    'full_name' => 'MUHAMMAD ARSHAKA AL GHOZALI',
    'nis' => '',
    'nisn' => '3208359923',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-10-13',
    'address' => 'DUSUN KRAJAN, DUSUN KRAJAN, Desa/Kel. Gondosuli, Kec. Pakuniran',
    'parent_name' => 'MUHAMMAD GHOZALI',
    'parent_phone' => '082312456765',
    'email' => 'muhammad.5@namira.school',
    'classroom_name' => 'A3',
  ),
  79 => 
  array (
    'full_name' => 'MUHAMMAD AYRES SYAHREZA',
    'nis' => '',
    'nisn' => '3203329799',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-02-05',
    'address' => 'DUSUN KURIPAN, JATIURIP, Kec. Krejengan',
    'parent_name' => 'REZA ANDHIKA',
    'parent_phone' => '081331229292',
    'email' => 'muhammad.6@namira.school',
    'classroom_name' => 'B3',
  ),
  80 => 
  array (
    'full_name' => 'MUHAMMAD AZKA AL FATIH',
    'nis' => '',
    'nisn' => '3205550294',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-05-04',
    'address' => 'JL.SUNAN BONANG, KRAKSAAN, Desa/Kel. Kraksaan Wetan, Kec. Kraksaan',
    'parent_name' => 'NURCHOLIS PUTRA NUGROHO',
    'parent_phone' => '081252522319',
    'email' => 'muhammad.7@namira.school',
    'classroom_name' => 'B3',
  ),
  81 => 
  array (
    'full_name' => 'MUHAMMAD AZLAN AL FATH',
    'nis' => '',
    'nisn' => '3192287252',
    'gender' => 'L',
    'pob' => 'BANYUWANGI',
    'dob' => '2019-12-26',
    'address' => 'JL.SAHARA, PERUM GRIYA MUTIARA BLOK C/23, Desa/Kel. Sidopekso, Kec. Kraksaan',
    'parent_name' => 'NOVAN SUSWANTO',
    'parent_phone' => '085222001771',
    'email' => 'muhammad.8@namira.school',
    'classroom_name' => 'B2',
  ),
  82 => 
  array (
    'full_name' => 'MUHAMMAD DINAR',
    'nis' => '',
    'nisn' => '3204602637',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-05-15',
    'address' => 'DUSUN KRAJAN, ALASKANDANG, Desa/Kel. Alas Kandang, Kec. Besuk',
    'parent_name' => 'DODIK',
    'parent_phone' => '082345678987',
    'email' => 'muhammad.9@namira.school',
    'classroom_name' => 'A3',
  ),
  83 => 
  array (
    'full_name' => 'MUHAMMAD FAHRI ABDILLAH',
    'nis' => '',
    'nisn' => '3200431643',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-10-31',
    'address' => 'DUSUN TIRTA, JABUNG SISIR, Desa/Kel. Jabungsisir, Kec. Paiton',
    'parent_name' => 'MUHAMMAD SAFARI',
    'parent_phone' => '085335595828',
    'email' => 'muhammad.10@namira.school',
    'classroom_name' => 'A1',
  ),
  84 => 
  array (
    'full_name' => 'MUHAMMAD FATIH HASAN',
    'nis' => '',
    'nisn' => '3207546772',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-12-04',
    'address' => 'DUSUN CANGAK, Desa/Kel. Sindet Lami, Kec. Besuk',
    'parent_name' => 'HASANUDDIN',
    'parent_phone' => '085233041839',
    'email' => 'muhammad.11@namira.school',
    'classroom_name' => 'A4',
  ),
  85 => 
  array (
    'full_name' => 'MUHAMMAD IBRAHIM FIRDAUS',
    'nis' => '',
    'nisn' => '3197822753',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-10-18',
    'address' => 'JL.YOS SUDARSO, KRAKSAAN WETAN, Desa/Kel. Kraksaan Wetan, Kec. Kraksaan',
    'parent_name' => 'AGUS WAHID',
    'parent_phone' => '085236456352',
    'email' => 'muhammad.12@namira.school',
    'classroom_name' => 'B2',
  ),
  86 => 
  array (
    'full_name' => 'MUHAMMAD LEUWIS ASH-SYATHIBI SOLEH',
    'nis' => '',
    'nisn' => '3200425276',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-03-09',
    'address' => 'DUSUN TAMAN, Sumberkembar, Kec. Pakuniran',
    'parent_name' => 'NORMA SHOLEH',
    'parent_phone' => '082302313442',
    'email' => 'muhammad.13@namira.school',
    'classroom_name' => 'B2',
  ),
  87 => 
  array (
    'full_name' => 'MUHAMMAD RAZKA TIRTA PRIYANTO',
    'nis' => '',
    'nisn' => '3191696498',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-11-12',
    'address' => 'JL SUNAN KALIJAGA, Kraksaan Wetan, Kec. Kraksaan',
    'parent_name' => 'SUGENG PRIYANTO',
    'parent_phone' => '085331870726',
    'email' => 'muhammad.14@namira.school',
    'classroom_name' => 'B2',
  ),
  88 => 
  array (
    'full_name' => 'MUHAMMAD RHAMZA ABDUL MALIKI',
    'nis' => '',
    'nisn' => '3205279508',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-12-06',
    'address' => 'DUSUN LUMBANG, LUMBANG, Desa/Kel. Sukokerto, Kec. Pajarakan',
    'parent_name' => 'ARSIMAN',
    'parent_phone' => '085234156134',
    'email' => 'muhammad.15@namira.school',
    'classroom_name' => 'A4',
  ),
  89 => 
  array (
    'full_name' => 'MUHAMMAD SYARIF HIDAYATULLAH',
    'nis' => '',
    'nisn' => '3208067487',
    'gender' => 'L',
    'pob' => 'BANYUWANGI',
    'dob' => '2020-02-28',
    'address' => 'GG.PLAMBOYAN, PERUM KEBUN AGUNG NO.74, Desa/Kel. Kebonagung, Kec. Kraksaan',
    'parent_name' => 'NUR AINI',
    'parent_phone' => '085342676897',
    'email' => 'muhammad.16@namira.school',
    'classroom_name' => 'B3',
  ),
  90 => 
  array (
    'full_name' => 'MUHAMMAD TAUFIQ HIDAYATULLAH',
    'nis' => '',
    'nisn' => '3203615124',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-11-02',
    'address' => 'DUSUN KAUMAN, DUSUN KAUMAN, Desa/Kel. Sukomulyo, Kec. Pajarakan',
    'parent_name' => 'YUSUF ARIF DARMAWAN',
    'parent_phone' => '0823542768987',
    'email' => 'muhammad.17@namira.school',
    'classroom_name' => 'A4',
  ),
  91 => 
  array (
    'full_name' => 'MUHAMMAD ZAFRAN AL HASBY',
    'nis' => '',
    'nisn' => '3213081968',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-05-12',
    'address' => 'DUSUN KRAJAN, BRANI KULON, Desa/Kel. Brani Kulon, Kec. Maron',
    'parent_name' => 'HASBY AL ROSIDY',
    'parent_phone' => '082315675768',
    'email' => 'muhammad.18@namira.school',
    'classroom_name' => 'A4',
  ),
  92 => 
  array (
    'full_name' => 'MUHAMMAD ZAHIER AFNAN FAQIH',
    'nis' => '',
    'nisn' => '3198850481',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-04-26',
    'address' => 'PERUM BUMI BULU INDAH F-11, BULU, Desa/Kel. Bulu, Kec. Kraksaan',
    'parent_name' => 'ACHMAD FAJAR',
    'parent_phone' => '0812678654467',
    'email' => 'muhammad.19@namira.school',
    'classroom_name' => 'A1',
  ),
  93 => 
  array (
    'full_name' => 'MUHAMMAD ZAIDUL AKBAR PUTRA NANDA',
    'nis' => '',
    'nisn' => '3209808855',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-10-25',
    'address' => 'DUSUN BERINGIN, TALKANDANG, Desa/Kel. Talkandang, Kec. Kotaanyar',
    'parent_name' => 'SUNANTO',
    'parent_phone' => '081567342567',
    'email' => 'muhammad.20@namira.school',
    'classroom_name' => 'A4',
  ),
  94 => 
  array (
    'full_name' => 'MUHAMMAD ZAYYAN ARKANA PRATAMA',
    'nis' => '',
    'nisn' => '3193263948',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-08-08',
    'address' => 'PERUM KRAKSAAAN LAND NO 63, KEBONAGUNG, Desa/Kel. Kebonagung, Kec. Kraksaan',
    'parent_name' => 'ALFA YULIANATA PRATAMA',
    'parent_phone' => '085675678987',
    'email' => 'muhammad.21@namira.school',
    'classroom_name' => 'B3',
  ),
  95 => 
  array (
    'full_name' => 'NADA INDAH THARA JANNAT MAULANA',
    'nis' => '',
    'nisn' => '3204855899',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-02-07',
    'address' => 'JL MAYJEN SUTOYO, Patokan, Kec. Kraksaan',
    'parent_name' => 'MAHARDIKA FIRMAN MAULANA',
    'parent_phone' => '085258880017',
    'email' => 'nada@namira.school',
    'classroom_name' => 'B4',
  ),
  96 => 
  array (
    'full_name' => 'NADHA FATIMAH SHAZIANUHA',
    'nis' => '',
    'nisn' => '3192582737',
    'gender' => 'P',
    'pob' => 'MALANG',
    'dob' => '2019-05-29',
    'address' => 'JL CANDI KALASAN III NO 14, BLIMBING, Kec. Blimbing',
    'parent_name' => 'MUHAMMAD ERLANGGA WICAKSONO',
    'parent_phone' => '081232775955',
    'email' => 'nadha@namira.school',
    'classroom_name' => 'B2',
  ),
  97 => 
  array (
    'full_name' => 'NAFISAH AL ILMI',
    'nis' => '',
    'nisn' => '3201697520',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-11-03',
    'address' => 'JL.MAYJEN PANJAITAN NO.12, SIDOMUKTI, Desa/Kel. Sidomukti, Kec. Kraksaan',
    'parent_name' => 'M. ZAINI BIN ALI WAFA',
    'parent_phone' => '081234567876',
    'email' => 'nafisah@namira.school',
    'classroom_name' => 'A3',
  ),
  98 => 
  array (
    'full_name' => 'NALA RAYYANA NUZULA',
    'nis' => '',
    'nisn' => '3211935691',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-05-06',
    'address' => 'DUSUN KRAJAN, PAITON, Desa/Kel. Jabung Candi, Kec. Paiton',
    'parent_name' => 'NUR KHOLIS MAJID',
    'parent_phone' => '081231456789',
    'email' => 'nala@namira.school',
    'classroom_name' => 'A1',
  ),
  99 => 
  array (
    'full_name' => 'NATHAN APRILIANO',
    'nis' => '',
    'nisn' => '3212920733',
    'gender' => 'L',
    'pob' => 'KOTA PROBOLINGGO',
    'dob' => '2021-04-12',
    'address' => 'DUSUN KEDUNGBAJUL, Desa/Kel. Kedungdalem, Kec. Dringu',
    'parent_name' => 'NADIA AURA YULITA',
    'parent_phone' => '085234191800',
    'email' => 'nathan@namira.school',
    'classroom_name' => 'A4',
  ),
  100 => 
  array (
    'full_name' => 'NAUFA AZZAHRA AZKAYRA ANDARU',
    'nis' => '',
    'nisn' => '3209220853',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-11-18',
    'address' => 'GAZA RESIDENCE F4, DUSUN KENARI, Desa/Kel. Sidopekso, Kec. Kraksaan',
    'parent_name' => 'SLAMET SRIAJI ANDARU',
    'parent_phone' => '082564768567',
    'email' => 'naufa@namira.school',
    'classroom_name' => 'A4',
  ),
  101 => 
  array (
    'full_name' => 'NAURA ZAIDA ALMAHYRA',
    'nis' => '',
    'nisn' => '3206090269',
    'gender' => 'P',
    'pob' => 'JEMBER',
    'dob' => '2020-05-02',
    'address' => 'DUSUN, STASIUN, Desa/Kel. Sukomulyo, Kec. Pajarakan',
    'parent_name' => 'MOCH ARIFIN',
    'parent_phone' => '085331247694',
    'email' => 'naura@namira.school',
    'classroom_name' => 'B4',
  ),
  102 => 
  array (
    'full_name' => 'NUR MUHAMMAD AZZAMNI',
    'nis' => '',
    'nisn' => '3199572749',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-10-25',
    'address' => 'DUSUN TENGAH, Besuk Kidul, Kec. Besuk',
    'parent_name' => 'ABDUL HAKIM',
    'parent_phone' => '081336863335',
    'email' => 'nur@namira.school',
    'classroom_name' => 'B2',
  ),
  103 => 
  array (
    'full_name' => 'QADISA NADYA PUTRI RACHMANI',
    'nis' => '',
    'nisn' => '3195893934',
    'gender' => 'P',
    'pob' => 'MALANG',
    'dob' => '2019-08-22',
    'address' => 'DUSUN TENGAH, Desa/Kel. Besuk Kidul, Kec. Besuk',
    'parent_name' => 'ARIK SASTRA YUDA BAHAGIA',
    'parent_phone' => '',
    'email' => 'qadisa@namira.school',
    'classroom_name' => 'B4',
  ),
  104 => 
  array (
    'full_name' => 'QIANZY RANUPATMA MAHESWARI',
    'nis' => '',
    'nisn' => '3204736870',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-05-22',
    'address' => 'DUSUN, KEBUN, Desa/Kel. Sukodadi, Kec. Paiton',
    'parent_name' => 'BAYU DWI PERMANA',
    'parent_phone' => '082227617193',
    'email' => 'qianzy@namira.school',
    'classroom_name' => 'B2',
  ),
  105 => 
  array (
    'full_name' => 'QUEENNA HAGIA SOPHIA',
    'nis' => '',
    'nisn' => '3203035974',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-07-10',
    'address' => 'VILA ILHAMI JL MINA RAYA 2 BLOK J-5 NO 23, PANUNGGANGAN BARAT, Desa/Kel. Panunggangan Barat, Kec. Cibodas',
    'parent_name' => 'NOER SYAMSI ZAKARIA',
    'parent_phone' => '082356786908',
    'email' => 'queenna@namira.school',
    'classroom_name' => 'A4',
  ),
  106 => 
  array (
    'full_name' => 'RADITYA KRISTIAN EKA PRATAMA',
    'nis' => '',
    'nisn' => '3204362821',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-04-10',
    'address' => 'JLN LETJEN MT HARYONO, SEMAMPIR, Desa/Kel. Semampir, Kec. Kraksaan',
    'parent_name' => 'EKA KRISTIANTO',
    'parent_phone' => '0821354876980',
    'email' => 'raditya@namira.school',
    'classroom_name' => 'A1',
  ),
  107 => 
  array (
    'full_name' => 'RAFIFAH ASILA ISMAIL HIDAYAT',
    'nis' => '',
    'nisn' => '3198842123',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-08-13',
    'address' => 'DUSUN LANDANGAN, Penambangan, Kec. Pajarakan',
    'parent_name' => 'RAHMAD HIDAYAT',
    'parent_phone' => '083854202866',
    'email' => 'rafifah@namira.school',
    'classroom_name' => 'B4',
  ),
  108 => 
  array (
    'full_name' => 'RAGHATA ANGKASA PUTRA WARDANA',
    'nis' => '',
    'nisn' => '3204490245',
    'gender' => 'L',
    'pob' => 'MALANG',
    'dob' => '2020-01-11',
    'address' => 'JL PERUM GARDEN PALMA B 13, JATIMULYO, Desa/Kel. Jatimulyo, Kec. Lowokwaru',
    'parent_name' => 'TRI WAHYU LAKSANA KUSUMA WARDANA',
    'parent_phone' => '08356437869876',
    'email' => 'raghata@namira.school',
    'classroom_name' => 'A3',
  ),
  109 => 
  array (
    'full_name' => 'RAISA QANITA FRANSISCA',
    'nis' => '',
    'nisn' => '3202927334',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-10-09',
    'address' => 'DUSUN TENGAH, Besuk Kidul, Kec. Besuk',
    'parent_name' => 'SONY FRANSISCA',
    'parent_phone' => '081234410400',
    'email' => 'raisa@namira.school',
    'classroom_name' => 'A4',
  ),
  110 => 
  array (
    'full_name' => 'RAMADHANI GIBRAN SYAHPUTRA NUGROHO',
    'nis' => '',
    'nisn' => '3199128890',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-05-30',
    'address' => 'PERUM KAMPOENG BAMBU BLOK B NO.1, Desa/Kel. Bulu, Kec. Kraksaan',
    'parent_name' => 'YESAYA HARYONO ADI NUGROHO',
    'parent_phone' => '082331028971',
    'email' => 'ramadhani@namira.school',
    'classroom_name' => 'B3',
  ),
  111 => 
  array (
    'full_name' => 'REIMAR EMIER FAWWAZ',
    'nis' => '',
    'nisn' => '3190536875',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-12-24',
    'address' => 'DUSUN BUKOLAN, BUKOLAN, Ganting Wetan, Kec. Maron',
    'parent_name' => 'RONI CAHYO UTOMO',
    'parent_phone' => '085222444567',
    'email' => 'reimar@namira.school',
    'classroom_name' => 'B2',
  ),
  112 => 
  array (
    'full_name' => 'REZA RAHADIAN BASUKI',
    'nis' => '',
    'nisn' => '3195115801',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-09-09',
    'address' => 'PERUM GREEN ROYAL, KEDOPOK, Desa/Kel. Kedopok, Kec. Kedopok',
    'parent_name' => 'RAKHMAD PUJI BASUKI',
    'parent_phone' => '081236789098',
    'email' => 'reza@namira.school',
    'classroom_name' => 'A1',
  ),
  113 => 
  array (
    'full_name' => 'SAGA ELLIO ATHARIAN',
    'nis' => '',
    'nisn' => '3190160144',
    'gender' => 'L',
    'pob' => 'MALANG',
    'dob' => '2019-06-02',
    'address' => 'DUSUN 3 PASAR 1, Klaseman, Kec. Gending',
    'parent_name' => 'SHANDY HARRY MULYONO',
    'parent_phone' => '085172206590',
    'email' => 'saga@namira.school',
    'classroom_name' => 'A1',
  ),
  114 => 
  array (
    'full_name' => 'SALMA ZELINE SAFEEA',
    'nis' => '',
    'nisn' => '3199920817',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-07-14',
    'address' => 'DUSUN KURIPAN, JATIURIP, Kec. Krejengan',
    'parent_name' => 'MUCHAMAD AINUL YAQIN',
    'parent_phone' => '082245940668',
    'email' => 'salma@namira.school',
    'classroom_name' => 'B4',
  ),
  115 => 
  array (
    'full_name' => 'SHAFIRA MEDINA AZZAHRA',
    'nis' => '',
    'nisn' => '3198488259',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-08-14',
    'address' => 'JL RAYA PANGLIMA SUDIRMAN 449, Desa/Kel. Semampir, Kec. Kraksaan',
    'parent_name' => 'FAJAR SETIAWAN',
    'parent_phone' => '081249322223',
    'email' => 'shafira@namira.school',
    'classroom_name' => 'B4',
  ),
  116 => 
  array (
    'full_name' => 'SHAUMA ABIDAH MARDIANTO',
    'nis' => '',
    'nisn' => '3190586022',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2019-05-28',
    'address' => 'DUSUN, KRAJAN, Desa/Kel. Bago, Kec. Besuk',
    'parent_name' => 'AGUS MARDIANTO',
    'parent_phone' => '085234375444',
    'email' => 'shauma@namira.school',
    'classroom_name' => 'B3',
  ),
  117 => 
  array (
    'full_name' => 'SHEZI AGACIA HALINA HUDA',
    'nis' => '',
    'nisn' => '3207490967',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-09-14',
    'address' => 'PERUM PAJARAKAN LAND BLOK H NO.14, Sukokerto, Kec. Pajarakan',
    'parent_name' => 'MUSTAHIQQUL HUDA',
    'parent_phone' => '081230414997',
    'email' => 'shezi@namira.school',
    'classroom_name' => 'A4',
  ),
  118 => 
  array (
    'full_name' => 'SYAFRINA LISA AZZAHRA',
    'nis' => '',
    'nisn' => '3205425619',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-04-22',
    'address' => 'DUSUN KARANG DAMPIT, KEBONAGUNG, Desa/Kel. Kebonagung, Kec. Kraksaan',
    'parent_name' => 'PEMPY DENDRA KUSUMA',
    'parent_phone' => '081231657980',
    'email' => 'syafrina@namira.school',
    'classroom_name' => 'A4',
  ),
  119 => 
  array (
    'full_name' => 'SYARIFATUL HASBIYAH MISSAYU',
    'nis' => '',
    'nisn' => '3203113115',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-11-28',
    'address' => 'JLN IR H JUANDA KAMPUNG BARU, PATOKAN, Desa/Kel. Patokan, Kec. Kraksaan',
    'parent_name' => 'HERMAN FELANI',
    'parent_phone' => '08234566768978',
    'email' => 'syarifatul@namira.school',
    'classroom_name' => 'A4',
  ),
  120 => 
  array (
    'full_name' => 'SYED SALIM BIN ALWI AL JUFRI',
    'nis' => '',
    'nisn' => '3192318401',
    'gender' => 'L',
    'pob' => 'SINGAPURA',
    'dob' => '2019-12-04',
    'address' => 'DUSUN WADUK DUSUN JABUNG CANDI, DUSUN WADUK DUSUN JABUNG CAND, Desa/Kel. Jabung Candi, Kec. Paiton',
    'parent_name' => 'ALWI ABDULLAH AL JUFRI',
    'parent_phone' => '081234213546',
    'email' => 'syed@namira.school',
    'classroom_name' => 'A4',
  ),
  121 => 
  array (
    'full_name' => 'SYIFA MUHAMMAD ASSEGAF',
    'nis' => '',
    'nisn' => '3201155460',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-05-08',
    'address' => 'DUSUN SLAMET, BULU, Desa/Kel. Bulu, Kec. Kraksaan',
    'parent_name' => 'MOCHAMMAD HODA ASSEGAF',
    'parent_phone' => '087762609556',
    'email' => 'syifa@namira.school',
    'classroom_name' => 'A4',
  ),
  122 => 
  array (
    'full_name' => 'TSAQIF ZIAUL HAQUE',
    'nis' => '',
    'nisn' => '3199995360',
    'gender' => 'L',
    'pob' => 'KEBUMEN',
    'dob' => '2019-05-24',
    'address' => 'DUSUN, KRAJAN II, Desa/Kel. Maron Wetan, Kec. Maron',
    'parent_name' => 'RAVI DINUL HAQUE',
    'parent_phone' => '081225575323',
    'email' => 'tsaqif@namira.school',
    'classroom_name' => 'B3',
  ),
  123 => 
  array (
    'full_name' => 'UNAISAH ALEENA KAMEELA',
    'nis' => '',
    'nisn' => '3203541315',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-03-24',
    'address' => 'PERUM GRIYA PALM RAHMANI BLOK A-10 NO 6, KEBONAGUNG, Desa/Kel. Kebonagung, Kec. Kraksaan',
    'parent_name' => 'YUSRI ASHER',
    'parent_phone' => '081231456765',
    'email' => 'unaisah@namira.school',
    'classroom_name' => 'A1',
  ),
  124 => 
  array (
    'full_name' => 'YUSUF SAKTI WIRATAMA WIDYANTORO',
    'nis' => '',
    'nisn' => '3219271928',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2021-04-12',
    'address' => 'JL WERKUDORO 49, SUMBERPUCUNG, Desa/Kel. Sumberpucung, Kec. Sumberpucung',
    'parent_name' => 'ALEX WIDYANTORO',
    'parent_phone' => '082345786908',
    'email' => 'yusuf@namira.school',
    'classroom_name' => 'A1',
  ),
  125 => 
  array (
    'full_name' => 'ZASKIA ANJANI PUTRI BURHANUDDIN',
    'nis' => '',
    'nisn' => '3207986672',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-07-18',
    'address' => 'PERUM WISMA PENGADANGAN BLOK A-5, KEBONAGUNG, Desa/Kel. Kebonagung, Kec. Kraksaan',
    'parent_name' => 'ARIF BURHANUDDIN',
    'parent_phone' => '085231654786',
    'email' => 'zaskia@namira.school',
    'classroom_name' => 'A4',
  ),
  126 => 
  array (
    'full_name' => 'ZAVIER RASHDAN HABIBI',
    'nis' => '',
    'nisn' => '3205096688',
    'gender' => 'L',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-06-19',
    'address' => 'JL. HASANUDDIN N0 80, Desa/Kel. Bulu, Kec. Kraksaan',
    'parent_name' => 'HABIBI',
    'parent_phone' => '081212677038',
    'email' => 'zavier@namira.school',
    'classroom_name' => 'A4',
  ),
  127 => 
  array (
    'full_name' => 'ZELMIRA PUTRI PRASODJO',
    'nis' => '',
    'nisn' => '3191384633',
    'gender' => 'P',
    'pob' => 'NGANJUK',
    'dob' => '2019-10-02',
    'address' => 'PERUM KRAKSAAN PERMAI D-5, KRAKSAAN, Desa/Kel. Sidopekso, Kec. Kraksaan',
    'parent_name' => 'ARIF SUMADYO PRASODJO',
    'parent_phone' => '085608582988',
    'email' => 'zelmira@namira.school',
    'classroom_name' => 'B4',
  ),
  128 => 
  array (
    'full_name' => 'ZOYA BAZLA ZAHIRA',
    'nis' => '',
    'nisn' => '3206110377',
    'gender' => 'P',
    'pob' => 'PROBOLINGGO',
    'dob' => '2020-04-06',
    'address' => 'DUSUN, KRAJAN, Desa/Kel. Tanjungsari, Kec. Krejengan',
    'parent_name' => 'RUDIYANTO',
    'parent_phone' => '082231814934',
    'email' => 'zoya@namira.school',
    'classroom_name' => 'B3',
  ),
);

        foreach ($studentsData as $item) {
            $email = trim($item['email']);
            $name = trim($item['full_name']);
            $nis = trim($item['nis']);
            $nisn = trim($item['nisn']);
            $gender = trim($item['gender']);
            $pob = trim($item['pob']);
            $dob = !empty($item['dob']) ? $item['dob'] : null;
            $address = trim($item['address']);
            $parentName = trim($item['parent_name']);
            $parentPhone = trim($item['parent_phone']);
            $classroomName = trim($item['classroom_name']);

            $classroomId = null;
            if (!empty($classroomName)) {
                // If name is like 'A2', map to 'TK A2' or keep 'A2'
                $nameForClass = $classroomName;
                if (preg_match('/^[AB]\d+$/', $classroomName)) {
                    $nameForClass = 'TK ' . $classroomName;
                }

                $level = str_contains($nameForClass, 'TK B') ? 'TK B' : 'TK A';

                $cls = Classroom::firstOrCreate([
                    'unit_id' => $unitId,
                    'name' => $nameForClass,
                ], [
                    'level' => $level,
                ]);

                $classroomId = $cls->id;
            }

            $password = $nis ? $nis : ($nisn ? $nisn : 'siswa123');

            $user = User::where('email', $email)->first();
            if (!$user) {
                $user = User::create([
                    'name' => $name,
                    'email' => $email,
                    'password' => Hash::make($password),
                ]);
            }

            if ($roleId) {
                DB::table('model_has_roles')->updateOrInsert([
                    'role_id' => $roleId,
                    'model_type' => 'App\\Models\\User',
                    'model_id' => $user->id,
                    'team_id' => $unitId,
                ]);
            }

            Student::updateOrCreate([
                'user_id' => $user->id,
                'unit_id' => $unitId,
            ], [
                'full_name' => $name,
                'nis' => $nis,
                'nisn' => $nisn,
                'gender' => $gender,
                'pob' => $pob,
                'dob' => $dob,
                'address' => $address,
                'parent_name' => $parentName,
                'parent_phone' => $parentPhone,
                'classroom_id' => $classroomId,
            ]);
        }
        echo "Berhasil mengimpor 129 Siswa TK Namira Kraksaan beserta Kelas!\n";
    }
}
